### ISSUE TITLE
location of aquatic variable sqlite db?

### ISSUE THREAD

**Issue by ChristopherTracey** [HeritageNetwork/Regional_SDM#10]
As we're working to move the lotic EnvVar to a sqlite version instead of a .csv file in order to increase model speed/performance, I have a quick question about its location.  Should it be a table in the main sqlite db, or should it be in its own separate sqlite?  

The current aquatic EnvVars table for CONUS is about 16GB.

**Comment by tghoward** [comment]
Sounds to me like it should be a separate sqlite db. That would make it more parallel to a raster stack or a folder of rasters.

**Comment by ChristopherTracey** [comment]
Ok. I was thinking the same thing. Thanks.
