### ISSUE TITLE
citation for code and open source statement

### ISSUE THREAD

**Issue by ChristopherTracey** [HeritageNetwork/Regional_SDM#110]
As we get closer to release, we should get a recommended citation for the SDM code as described here
https://help.github.com/articles/referencing-and-citing-content/

Also, some sort of open source statement.

**Comment by tghoward** [comment]
All set to go for zenodo (switch flipped), but we should wait till we are at a pre-release stage. I almost pulled the trigger but thought it best to wait.

**Comment by tghoward** [comment]
Done!  DOI tag added to bottom of each repository ReadMe.
