### ISSUE TITLE
populate ModelerID 

### ISSUE THREAD

**Issue by tghoward** [HeritageNetwork/Regional_SDM#112]
@ChristopherTracey in order to address the requested metadata citation refinement (ID modeler), we should populate the `lkpModelers` table and the `ModelerID` field in the `lkpSpecies` table.  Use ModelerID = 3 for PA, and I'll use NY = 4 as those were the values from the Eastern Regional Project.

**Comment by ChristopherTracey** [comment]
Sounds good. I was thinking along these lines.

**Comment by tghoward** [comment]
done here: 98cb078c2349aa52dfd03ec9c51d773bf61337c5
