### ISSUE TITLE
Look into mapview package for metadata maps?

### ISSUE THREAD

**Issue by matthewpaulking** [HeritageNetwork/Regional_SDM#116]
As a follow up to the metadata MoBI tech team call, I thought you might like to check out the `mapview` package: https://r-spatial.github.io/mapview/index.html. There is a function `mapshot` that allows you to take a static snapshot of a Leaflet map. Among other things, this would allow you to use any tiled basemap as the background. For instance, I've pasted two different `mapshot` outputs with different basemaps, saved as PNG files. `mapview` handles `raster`, `sp`, and `sf` classes, so there's some good flexibility on what final maps could contain. Just some food for thought, and might save some heavy lifting on map output.

By the way, you all have done an excellent job with the metadata template and typesetting. Working with LaTeX is no picnic! :+1:

![image](https://user-images.githubusercontent.com/32152670/51559169-79190800-1e3e-11e9-8af4-33c7611e66e6.png)

![image](https://user-images.githubusercontent.com/32152670/51559513-563b2380-1e3f-11e9-9f0b-f38e369a96a0.png)

**Comment by ChristopherTracey** [comment]
Thanks. I haven't used `mapview` before. We'll look into it.

Yes, Latex isn't the easiest, but we're learning!

**Comment by tghoward** [comment]
@matthewpaulking  Excellent. Thanks for the tip. I've worked a fair amount with ggmap, but this looks more flexible in this context. I'm on it.

**Comment by tghoward** [comment]
It looks like a problem with mapview is the lack of flexibility for modifying the legend (you can't). Which makes sense for it's purpose -- a dynamic gui for map viewing. Mapshot is like an afterthought. But with that said, if we want to use basemaps (not positive yet), I like it.  Current output:


![mapfig-1](https://user-images.githubusercontent.com/6129193/52061238-e104d800-253b-11e9-98c0-9ea6c0c9ff94.png)

**Comment by matthewpaulking** [comment]
Hmm, I didn't know about the inflexibility of the legend. I would think the legend is flexible within the `leaflet` package, wonder if a leaflet map can just be piped out with `mapshot`?

**Comment by tghoward** [comment]
Found tmap, which imports mapview, and does all we want. Mapping is so dynamic in R these days! see #139

**Comment by matthewpaulking** [comment]
Yes, indeed! Things are moving fast in the R package world. Glad you found a solution!

**Comment by ChristopherTracey** [comment]
@tghoward - any tips on making tmap work for vector data for the Aquatics?

Reopening this until I get the aquatic branch working.

**Comment by ChristopherTracey** [comment]
I got this more or less working for the Aquatics.  Two outstanding issues are:
1. Incorporating the area based polygons
2. There doesn't seem to be an option for a 'title' field in `tm_lines` (its in `tm_polys`, but not in `tm_dots`???).  It errors out if we try to include it. We may need to find an alternative way to say "modeled suitability")

**Comment by tghoward** [comment]
@ChristopherTracey I can work on this if you can provide examples of what you need. 
tim

**Comment by ChristopherTracey** [comment]
@tghoward, here's what I'm currently getting for my map legend:
![image](https://user-images.githubusercontent.com/8216371/54209595-7046c900-44b4-11e9-96de-e3a518d7c2cb.png)

The boxes label 'pred' are from the NHD Area polygons. I would like to drop them from the legend, so only the lines above are shown.

The 'prbblty' title above the line legend needs to be changed to "modeled suitability"

**Comment by ChristopherTracey** [comment]
Here's that section of code for ref:
```
qtm(basetiles) + 
  tm_shape(results_shape) + # results_shape$prbblty
    tm_lines(col="prbblty", palette=clrs, labels=c("Low Habitat Suitability", rep(" ", nclr-2), "High Habitat Suitability")) + # title="modeled suitability",    
  tm_shape(area.wb.pred) + # waterbodies and NHD polys
    tm_fill(col="pred", palette=clrs) + 
  tm_shape(referenceBoundaries) +
    tm_borders(col = "grey", lwd = 1) + 
  tm_shape(studyAreaExtent) + 
    tm_borders(col = "red", lwd = 2) + 
  tm_compass(north = 0, type = "arrow", position = c("left","bottom")) + 
  tm_scale_bar()
```

**Comment by tghoward** [comment]
Perhaps you can push your current branch (with this code) up to github so I can try to plot?

**Comment by tghoward** [comment]
Wait ... I can just work in _Aquatic. I don't need you to push anything.

**Comment by tghoward** [comment]
It looks like this code fixes those two problems:
```
qtm(basetiles) + 
  tm_shape(results_shape, name="modeled suitability") + # stream linework
    tm_lines(col="prbblty", palette=clrs, labels=c("Low Habitat Suitability", rep(" ", nclr-2), "High Habitat Suitability"),
             title.col = "modeled suitability") +     
  tm_shape(area.wb.pred) + # waterbodies and NHD polys
    tm_fill(col="pred", palette=clrs, legend.show = FALSE) + 
  tm_shape(referenceBoundaries) +
    tm_borders(col = "grey", lwd = 1) + 
  tm_shape(studyAreaExtent) + 
    tm_borders(col = "red", lwd = 2) +
  tm_compass(north = 0, type = "arrow", position = c("left","bottom")) + 
  tm_scale_bar()
```

**Comment by tghoward** [comment]
I've saved `MetadataEval_knitr.rnw` in Aquatic, but have not committed.

**Comment by ChristopherTracey** [comment]
Sorry, just got out of another meeting. It’s up on my fork, but we can PR to HeritageNetwork

**Comment by ChristopherTracey** [comment]
I just made the changes on my copy and tested. Works great! Thanks!  
I can push it up and PR it over.

**Comment by ChristopherTracey** [comment]
Merge in #153.
