### ISSUE TITLE
threshold used in validation loop

### ISSUE THREAD

**Issue by tghoward** [HeritageNetwork/Regional_SDM#118]
based on @emiliehenderson 's question about what threshold used in the validation loops. It currently is the mean of an estimate of the upper left corner of the ROC curve. So therefore a single value applied to all LOO runs. I'd like to change that to calculating a value for each loop. Does anyone have a preference on threshold metric? How about maxSSS (https://onlinelibrary.wiley.com/doi/full/10.1002/ece3.1878). @ChristopherTracey , ok?

**Comment by ChristopherTracey** [comment]
I'm fine with that based on the Lui et al paper, the fact that we present maxSSS in Table 3 (and that we also dropped the Upperleft of the ROC plot from that table a while ago), and previous experience using maxSSS for this purpose when I used to run MaxEnt models.  Ok, that last reason was just to jab @tghoward a little...

Let's make it so!

**Comment by tghoward** [comment]
see #120 . @ChristopherTracey would it be easiest for me to merge for you to check out?

**Comment by ChristopherTracey** [comment]
If you would like to do the merge, that would be great!

**Comment by ChristopherTracey** [comment]
Re-opening based on our conversation earlier in the week on how the choice of maxSSS may be affecting TSS values.

**Comment by ledugan** [comment]
Out of curiosity, how might maxSSS affect TSS? We have more-or-less settled on using maxSSS for our purposes here, so I'm wondering if I need to reconsider that decision.

**Comment by tghoward** [comment]
That's actually what we recently switched to, see: https://github.com/HeritageNetwork/Regional_SDM/blob/a08dac7968d39096f8811e7f3304b7c27cbc9f03/3_createModel.R#L428 

At least that what I was trying to do. QC'ing those lines would be good!

I think that's what was causing the changes @ChristopherTracey noted in the aquatic branch.

**Comment by tghoward** [comment]
Wait ... @ledugan , that's what you were saying. Sorry I'm a bit scattered right now.

**Comment by ChristopherTracey** [comment]
I ran some additional models and maxSSS seems to work ok. However, and this will be of interest to you @ledugan, for some models like the Rio Grande Cooter, its drastically downgraded the TSS score. I'm not sure why, but I wanted to see if there was another threshold that may be 'less variable' than maxSSS across model runs. Maybe that's a bad idea though.

**Comment by tghoward** [comment]
Ooof. @ledugan @ChristopherTracey I think I found a bug in #120 I'm going to post a fix as well as flip to MTP for now. I'm leaving maxSSS in so either of you can try both (without the bug!) and see how it behaves. Hopefully much better.

**Comment by tghoward** [comment]
see #133

**Comment by ledugan** [comment]
Interesting, @ChristopherTracey I poked around in the literature some trying to find something that might explain this, but haven't found anything yet. Is there a pattern for the models it has an effect on (e.g., aquatic species, a particular taxonomic group)?

**Comment by tghoward** [comment]
Sticking with MTP for now, and closing. Open up again if anyone has suggestions or improvements.
