### ISSUE TITLE
handle polys, points, or both

### ISSUE THREAD

**Issue by tghoward** [HeritageNetwork/Regional_SDM#12]
The terrestrial scripts are going to need to be able to handle polygon only inputs (EO data), points only inputs (observations), and cases where we have both.

**Comment by ChristopherTracey** [comment]
Why don't we just add a minimal (i.e. 25m) buffer to the observation points and use the polygon case?

**Comment by tghoward** [comment]
hmm, because I'd want points to group at a scale different than that? And I wouldn't want to put multiple points in that kind of polygon, but the standard polygon case would? They seem pretty different to me.

**Comment by ChristopherTracey** [comment]
I can't speak to your grouping question, but on the multiple points front:
1) how many points would get placed in a small buffer?
2) The equivalent RA for many of the observation datasets are typically going to be fairly low, so fewer points would be placed anyway.

**Comment by tghoward** [comment]
The classic approach for observations is to 'thin' them by removing points very close to each other. I've been thinking we'd be able to keep them all and use the approach discussed in one of the tech calls (basically group them up). How would we handle that in the 'convert to a small buffered polygon' case? I guess we'd need to group up the polys and have multipart polys.

**Comment by ChristopherTracey** [comment]
It seems buffering, merging, and placing random points into polygons based on the observations would help us retain more of the observation data, versus the classical thinning approaches.

(_I'm open to whatever you think is best though_)

**Comment by tghoward** [comment]
Yes, I don't want to thin points.  I had been thinking I'd rather use clusters of original observation points instead of newly placed random points inside polygons made from clusters of observation points.  But with only a few observations that idea could be less powerful than incorporating the spatial precision of the observations (meaning make polygons from observations based on spatial precision), if that is available.

**Comment by tghoward** [comment]
... we ended up using the approach of buffering points to make polys ...
