### ISSUE TITLE
presence file schema

### ISSUE THREAD

**Issue by dnbucklin** [HeritageNetwork/Regional_SDM#14]
Have there been some thoughts on a presence file schema? It would be great to have the same file setup for both aquatic and terrestrial presences.

Right now for aquatics the scripts expect a `csv` file with the columns:

COMID | huc12 | group_id | EO_ID_ST | SCOMNAME | SNAME | OBSDATE
-- | -- | -- | -- | -- | -- | --

And for terrestrial we expect a shapefile with the columns:

EO_ID_ST | SNAME | SCOMNAME | SFRACalc | OBSDATE
-- | -- | -- | -- | --

It would be nice to have shapefiles (e.g., points, lines, or polygons) as expected input, and the same table schema for both. I'd propose:

UID | SPECIES_CODE | EO_ID_ST | GROUP_ID | SFRACalc | OBSDATE
-- | -- | -- | -- | -- | -- 
unique feature ID | character code for species | biotics EO_ID (can be NA) | numeric group id | ra value; numeric? | yyyy-mm-dd or NA

Any other columns or ideas for this?

**Comment by tghoward** [comment]
I agree it would be very good to have the same schema. I see `group` and `eo_id` as not that different, and perhaps even equivalent. Do you typically have one of them at a finer scale that the other? Perhaps we only need a `group_id` and, when available, this becomes `EO_ID_ST`? 

The other field that might be good would be `EGT_ID`  the element global ID from natureserve. Which, admittedly is redundant with `species_code`, but probably better for tracking, albeit more opaque. 

I agree we don't need `scomname` and `sname`

I'm intriqued by `SFRACalc`. How are you calculating RF?

**Comment by tghoward** [comment]
I thought `EO_ID_ST` was our grouping variable. And thus would be at a higher level than an observation level ID.

**Comment by ChristopherTracey** [comment]
But `GROUP_ID` seems to be surplanting that use.

**Comment by tghoward** [comment]
Oh, I guess I understand what you were saying. Wouldn't those values also go to the `UID`?

**Comment by ChristopherTracey** [comment]
`EGT_ID` is probably the more useful choice here overall, but `SPECIES_CODE` might be needed if we're modeling a species not represented in the NS taxonomy.

**Comment by tghoward** [comment]
> I'd see `GROUP_ID` as the grouping variable for the model cross-validation, however that ends up being calculated (EO_ID, sep. distance, etc). If we calculate that in preprocessing, then `EO_ID_ST` wouldn't be a necessary column for the modeling process.

Agreed. It (`GROUP_ID`) would be (is) also used in the sampsize vector, which is key. 

> 
> I'm fine with either `EGT_ID` or `SPECIES_CODE`, but is there any reason to have both(?)
> 

Chris makes a good point about some species not having an `EGT_ID` ... hmm but we do have a final list and we do have ID's for all of them, so we might be good there. Operationally it is much more opaque to use the ID. Do we want folders labeled "123345" or "cutecode"? Actually, we could do lookups to the sqlite db and still use "cutecode" even though the input data only have `EGT_ID`.

**Comment by ChristopherTracey** [comment]
I was more so thinking for the future in regards to nonstandard codes, as you said we're good for MoBI. Maybe we just make sure is a character field and be done with it.   I'm pro "cutecode" for folder names though.

**Comment by dnbucklin** [comment]
I like the cutecode for folder names too; I'd lean towards that for the input file as well if there are any species without an assigned EGT_ID as Chris suggested.

So it seems like the minimal SDM input file could be:

UID | SPECIES_CODE | GROUP_ID | RA | OBSDATE
-- | -- | -- | -- | --
unique feature ID | character code for species | numeric group id | ra value | yyyy-mm-dd or NA

...and maybe huc_12 depending how/when it is assigned.

This is probably a larger discussion or maybe is in the works already, but this SDM input file could be a subset of a (database) table with `UID` being the primary key, which stores the additional columns on original data source, original data source ID, etc.

**Comment by ChristopherTracey** [comment]
I like @dnbucklin's minimal input file with the caveat that we're not currently using RA for aquatics so we may want to allow NA values.

Let's move HUC12 to be handled within script--its actually in the EnvVar table so we can attribute it from there. I'll mark it as an issue.

**Comment by ChristopherTracey** [comment]
Just for clarification, for the aquatics input files, we're storing the COMID in the `UID` column, right?

**Comment by ChristopherTracey** [comment]
Ok. We can make that change, so that `COMID != UID`.

Regarding your final question, yes. We recently made significant improvements to the grouping tool to select and then hand edit the selection of COMIDs.  See: https://github.com/PNHP/SDM_Tools

**Comment by dnbucklin** [comment]
Looks right to me, only thing I'd suggest is to put `COMID` first since it's the unique key for this table (right?).

**Comment by dnbucklin** [comment]
To be consistent with terrestrial I was thinking of `UID` coming from the original occurrence table, e.g. the ID of the unique feature (e.g. Source Feature) that you can pull `RA` and `OBSDATE` from, if possible. If the same occurrence feature links to multiple reaches/COMIDs, it would be duplicated in the resulting reach table. So maybe `FEAT_ID` would be a better name than `UID`.

**Comment by ChristopherTracey** [comment]
@tghoward, we should check in on this and make sure both branches are aligned.

**Comment by tghoward** [comment]
> So the aquatic input file will look like:
> 
> UID	COMID	SPECIES_CODE	GROUP_ID	RA	OBSDATE
> unique feature ID	NHD COMID	character code for species	numeric group id	ra value or NA	yyyy-mm-dd or NA

@ChristopherTracey I don't think RA should be allowed to be `NA`.  Is there a reason you are allowing in this table?

**Comment by tghoward** [comment]
arggh. Sadly, SPECIES_CODE is greater than 10 chars and thus a problem for shapefiles. Those natty shapefiles. I'm modifying to use `SPECIES_CD` in the terrestrial branch.

**Comment by ChristopherTracey** [comment]
There's a check for `NA` in script1 on Terrestrial right? It's not a required column in Aquatic.

**Comment by tghoward** [comment]
Done for terrestrial in https://github.com/HeritageNetwork/Regional_SDM/pull/101

All terrestrial inputs are now expecting these columns:
c("UID", "GROUP_ID", "SPECIES_CD", "RA")

**Comment by tghoward** [comment]
I think we are good here.
