### ISSUE TITLE
NA values in aquatic variables

### ISSUE THREAD

**Issue by ChristopherTracey** [HeritageNetwork/Regional_SDM#15]
What happens in the scripts if there are NAs in the EnvVar data? Will it fail? Or just not predict for that flowline?

Related to this, I believe that there are areas of the US where we may have more NAs in certain variables (i.e. the desert southwest).  Do we need to add something to the code where after the project area is limited to certain HUCs (based on the species range), it drops any variables that have NA values?

**Comment by tghoward** [comment]
Classically RF will return an NA and not fail. I don't know what happens in your case, though. Try it?

If the variables are important to you they can be imputed. But that gets kind of circular.

**Comment by dnbucklin** [comment]
The code as-is drops the **records** with NAs for any variable, so I think you're right, we would want to pre-screen variables to have some level of data-completeness after we've limited the project area.

**Comment by tghoward** [comment]
makes sense to me. I'd expect all our rasters to be complete so hopefully won't have this problem on the terrestrial side. But you never know and so it might make sense to have this in master. Certainly should trigger a warning and then the variable could be removed. Need to be careful as the removed variables might be useful/important.

**Comment by ChristopherTracey** [comment]
Thanks.  I'll dig into a potential approach a little more.
