### ISSUE TITLE
encoding error

### ISSUE THREAD

**Issue by ChristopherTracey** [HeritageNetwork/Regional_SDM#163]
@tghoward, are you getting (or have you got) this error in the metadata step?

`! Package inputenc Error: Invalid UTF-8 byte 147.`

I can't seem to get around it.

**Comment by tghoward** [comment]
@ChristopherTracey , um, nope, have not seen it. Need a little more information. If it is in `knit2pdf` there are details in the tex log file.

**Comment by ChristopherTracey** [comment]
This is probably the most relevant part of the .log

```
(C:\Users\Christopher\AppData\Roaming\MiKTeX\2.9\tex\latex\ucs\uni-global.def
File: uni-global.def 2013/05/13 UCS: Unicode global data
)
\uc@secondtry=\count88
\uc@combtoks=\toks17
\uc@combtoksb=\toks18
\uc@temptokena=\toks19
)
! Missing number, treated as zero.
<to be read again> 
                   B
l.54 \DeclareUnicodeCharacter{B0}{$^{\circ}$}
```

**Comment by ChristopherTracey** [comment]
Maybe related to this: https://github.com/yihui/knitr/issues/1343

**Comment by ChristopherTracey** [comment]
I went back to the `knit` and `call` method and dropped `knit2pdf` and it works fine. I'm going to go with that for now and not worry about this encoding issue at this time.

**Comment by tghoward** [comment]
Can you send me the entire life file? I'd guess that one of the objects getting pulled from a DB has a bad character

**Comment by tghoward** [comment]
Especially since it is species specific

**Comment by ChristopherTracey** [comment]
Yeah, however, I deleted it after I got the other version working. I'll switch it back and rerun it.

It was happening across all species--could it be in Access Tracking db?

**Comment by tghoward** [comment]
Interesting .. I had a heck of a time moving some fields up to the SQL Server DB because of some crazy encodings in the Access DB. In this case they were all in comments fields in which text was copy-pasted from emails or other sources.  Perhaps things will be cleaner now that we are grabbing data from SQL Server tables ...

**Comment by ChristopherTracey** [comment]
Hopefully.

**Comment by tghoward** [comment]
closing this for now, can re-open if the issue pops up again
