### ISSUE TITLE
subset data for pplots

### ISSUE THREAD

**Issue by tghoward** [HeritageNetwork/Regional_SDM#164]
@ChristopherTracey no, I had not been using the two lines that subset the data before creating partial plots ... the result of which speeds up the partial plot creation:

https://github.com/HeritageNetwork/Regional_SDM/blob/ba8c95fe63dcf50365783e783db9335db189702b/3_createModel.R#L529

Thanks for mentioning it. I'm worried though, that it subsamples over all rows (I think) so if there are very few presence rows, it will preferentially include background rows, and perhaps even miss presence rows altogether. Shouldn't it subsample within each pres/abs group?  Also it chooses column by number, which seems dangerous.  I agree 10,000 rows is probably enough for the pplots, so I'll try to get something like it into the terrestrial branch. 
Tim

**Comment by ChristopherTracey** [comment]
Perhaps. I never really looked at it and was just happy it "works".  I haven't seen much about in the pplots that looks weird, but again, interpretation of those have a lot of unanswered questions.

Should we compared some original pplots versus the sampled method?

**Comment by tghoward** [comment]
done. c8d419a0cb439a1dd86ba11c0d116b23455488e9
