### ISSUE TITLE
Writing the Aquatic metadata map is really slow for large areas under tmap

### ISSUE THREAD

**Issue by ChristopherTracey** [HeritageNetwork/Regional_SDM#165]

**Comment by dnbucklin** [comment]
Lowering the DPI of the saved PNG speeds this up a bit. It's set to 600, but I went down to 200 and the quality isn't noticeably different, unless you zoom in close on the PDF. This also saves a lot of size on the metadata file.
https://github.com/HeritageNetwork/Regional_SDM/blob/67b652c05fc5d383083b0669b8f950bd4f27757a/MetadataEval_knitr.rnw#L385

**Comment by tghoward** [comment]
@ChristopherTracey  perhaps try the simplify option in tm_shape https://www.rdocumentation.org/packages/tmap/versions/2.2/topics/tm_shape  you'd apply it to this line   tm_shape(results_shape, name="modeled suitability") + # stream linework

**Comment by tghoward** [comment]
I see DPI changes and simplify (simplify commented out) in the current version of the code so this seems to have been addressed.
