### ISSUE TITLE
mtry: reset to valid range

### ISSUE THREAD

**Issue by ChristopherTracey** [HeritageNetwork/Regional_SDM#172]
This warning appeared at the end of the one of the model runs.  It disappeared upon a second run of the same species.  Documenting here in case it pops up again.

```
Warning messages:
1: In randomForest.default(trSet[, indVarCols], y = trSet[,  ... :
  invalid mtry: reset to within valid range
2: In randomForest.default(trSet[, indVarCols], y = trSet[,  ... :
  invalid mtry: reset to within valid range
3: In randomForest.default(trSet[, indVarCols], y = trSet[,  ... :
  invalid mtry: reset to within valid range
```

**Comment by tghoward** [comment]
It looks like one reason for this error is that mtry defined as a value larger than the number of env vars. That scenario is possible as we tune for mtry before removing correlated vars and vars of low importance.  TODO: check and trap that edge case.

**Comment by tghoward** [comment]
I think we fixed this

**Comment by ChristopherTracey** [comment]
Ok. I can't remember if we did.

**Comment by mukaddim98** [comment]
The mtry is the number of variables randomly sampled as candidates at each split. So, if you set your mtry to a value, let's say, greater than the total number of features, your mtry is no longer "within valid range".
