### ISSUE TITLE
Attribute presence reaches with HUC12 

### ISSUE THREAD

**Issue by ChristopherTracey** [HeritageNetwork/Regional_SDM#18]
As referenced in #14, we're going to drop the HUC12 field from the input dataset and assign it from EnvVars table.  It's currently used in [1_pointsInPolys_cleanBkgPts.R](https://github.com/HeritageNetwork/Regional_SDM/blob/aquatic/1_pointsInPolys_cleanBkgPts.R), but we don't hit the EnvVars until [2_attributePoints.R](https://github.com/HeritageNetwork/Regional_SDM/blob/aquatic/2_attributePoints.R), sio we'll have to rearrange some things.

**Comment by dnbucklin** [comment]
Really late on this, but I like dropping HUC12 from the presence file. I think it makes sense to store in a minimal "all reaches" shapefile/table (`nm_allflowlines`), with just [`comid`, `huc12`, {geometry}].

Then the EnvVars table could be clean with just `comid`, `var1`,`var2`, etc.).

**Comment by dnbucklin** [comment]
Working through the scripts today, I'm reminded we also use the columns `wacomid` (the NHD area comid) and `strord` (stream order), which are both used for plotting in the metadata. So it's probably good to retain those columns in `nm_allflowlines` also.

**Comment by ChristopherTracey** [comment]
Good catch.

**Comment by dnbucklin** [comment]
closing as huc12 is now handled in sqlite background DB #32 and discussion moved to #27
