### ISSUE TITLE
add test for GDAL on the Path

### ISSUE THREAD

**Issue by matthewpaulking** [HeritageNetwork/Regional_SDM#181]
The call to `system("gdalwarp <etc...>")` will silently fail if GDAL is not on the Path. `stack(newL)` couldn't find any rasters in the temp directory, and would return an error saying it couldn't find the rasters at the paths given. I think it could be a good idea to explicitly test for the existence of GDAL in `run_SDM.r` with something like the following options:

```r
#  1. Test the PATH in R environment
grepl("OSGeo4W64", Sys.getenv("PATH"))

#  2. Try a test command with a system call
gdal_test <- try(
    suppressWarnings(
        system2('gdalinfo', stdout = T)
    )
)
if(class(gdal_test) == "try-error"){
    stop(call. = FALSE, "You need to have C:\OSGeo4W64\bin on the Path")
}
```

Same test could go for MiXTeX.

**Comment by tghoward** [comment]
Ok, done in #183 .  I used your first suggestion (using `Sys.getenv` ) ... one potential problem is that GDAL could be installed via a different route than OSGeo4W64, and there could be a different TeX interpreter than MiKTeX, but that's for improvements at a later date, I suppose.
