### ISSUE TITLE
database schema

### ISSUE THREAD

**Issue by dnbucklin** [HeritageNetwork/Regional_SDM#19]
Since I originally volunteered to handle this, I'm assigning myself to it. It seems like we need to settle on at least a working database schema, or we'll be running into a lot of merge conflicts...

Right now in the `sqlite` folder, there is Tim's latest database schema (`sqliteDBDump.txt`) and the one I had recently updated (`sqlite_template_db_nodata.sql`), which has a tracking scheme for input presence files and is used in all the recent updates I've made. 

I can merge these with naming in favor of `sqliteDBDump.txt`, but also includes the features and tables I've added (`tblVarsUsed` and `lkpEnvVarsAqua`). Does that seem like a good plan? Any features still missing from either database we'd like to add?

**Comment by tghoward** [comment]
Excellent, go for it. I think there are still things missing, particularly the range information, which I don't think I got the most recent iteration in there. In looking at what Wyoming had from their presentation, I put together something like this that I thought could work better:

CREATE TABLE "lkpRange" ( `range_id` INTEGER PRIMARY KEY AUTOINCREMENT, `EGT_ID` INTEGER, `huc10_id` TEXT, `origin` TEXT, `occurrence` TEXT, `version_info` TEXT, `comments` TEXT )


![rangetable](https://user-images.githubusercontent.com/6129193/47042728-0a9b1e80-d15a-11e8-9da1-f24c4958f96e.png)

There may be other levels of HUC we may want to add to it. 

Tim

**Comment by ChristopherTracey** [comment]
I would like to propose that we split `lkpEnvVarsAqua` into `lkpEnvVarsAquaLotic` and `lkpEnvVarsAquaLentic` as we are currently running these two model types separately. If not, can we add an aquatic variable type field that we can query on?

**Comment by ChristopherTracey** [comment]
@tghoward, regarding:
> There may be other levels of HUC we may want to add to it.

Why don't we just handle the other HUC levels by dynamically subsetting the HUC10 field?

**Comment by tghoward** [comment]
@ChristopherTracey good question - that's why I was wishy-washy ("may be... may want to"). The primary reason would be that if we have many thousands records then I expect string subsetting will be much slower than native SQL lookup queries.  We need to think about efficiencies and timing ....

**Comment by ChristopherTracey** [comment]
I just tested in on 2,798,311 rows (the number of reaches in the NHD-MR) and it took 0.466 seconds to subset HUC12 to HUC6 in R.  Are we going to get much bigger than that?

There's also the SQL `SUBSTRING` which we could call from the SQL queries and might be faster.

**Comment by tghoward** [comment]
Ok, sounds good!

**Comment by dnbucklin** [comment]
The database was updated and all branches are using the same schema as of 14870c9d. Use `preprocessing/preproc_getCleanSqliteDB.R` to create a new database. The minimal database edits to get started are:

- assign a model type (`modtype`) to the species you are modeling in the `lkpSpecies` table (see `lkpModtype` for types and add a new one if needed)
- populate the `use_[modtype]` column in the `lkpEnvVars[Aqua]` tables with standard variables to use for that `modtype`
   - note that `A` (base aquatic) and `T` (base terrestrial) are already populated based on Virginia projects

Leaving this issue open as I'm sure we have more to do on the DB...

**Comment by tghoward** [comment]
closing this. `modtype` is fully applied (A, T, S) based on Tracking Database and `preprocessing\preproc_populate_lkpSpeciesTable.R`  So, right now we aren't separating out R or L options in `lkpEnvVarsAqua`.  Not sure we have the info to parse that correctly. 

Other DB changes should be brought up as new issues.
