### ISSUE TITLE
AquaGroup: incorrect cutoff specified

### ISSUE THREAD

**Issue by ChristopherTracey** [HeritageNetwork/Regional_SDM#203]
pletcica failed with the following issue: 

> Error in predict.randomForest(trRes[[i]], evSet[[i]], type = "response",  : 
>   Incorrect cutoff specified.
> In addition: Warning message:
> In min(allVotesPrespts, na.rm = TRUE) :
>   no non-missing arguments to min; returning Inf

It only has three training groups so it may be related to that.

**Comment by ChristopherTracey** [comment]
Also happens with eurynana, which also only has three groups.

**Comment by tghoward** [comment]
Ok, I've tracked this down to this problem. When there is only one record (stream reach) per group in *all* cases of the subset used to build the training set in the validation loop, then our sample size vector (ssVec) has to pull all of them to build each tree in the forest. The result is no OOB presence records so the error is NaN. This trickles down to the errors above. 

A good edge case that we need to trap. I'll have to chew on it a bit.

**Comment by tghoward** [comment]
Taking back what I said above, I've got a grouping solution that may work generally (and at least works for both pletcica and eurynana). Will PR it soon.
