### ISSUE TITLE
df.in2 not found

### ISSUE THREAD

**Issue by ChristopherTracey** [HeritageNetwork/Regional_SDM#206]
@tghoward I'm getting this error in script 3 now. Is this a result of the move of that singleton fix to outside the validation loop?

`Error in grep(mergeGroup, df.in2$group_id) : object 'df.in2' not found`

**Comment by tghoward** [comment]
Yep, that was it. Fixed in here:  https://github.com/ChristopherTracey/Regional_SDM/pull/27

**Comment by ChristopherTracey** [comment]
What about the `mergeLocation <- grep(mergeGroup, df.in2$group_id) - 1` line two lines up from there as well?  Should that be `df.in$group_id` as well?

**Comment by tghoward** [comment]
yes, change that too. Whoops.

**Comment by ChristopherTracey** [comment]
I'll take care of it. Thanks!
