### ISSUE TITLE
full filename for nm_presfile?

### ISSUE THREAD

**Issue by tghoward** [HeritageNetwork/Regional_SDM#24]
https://github.com/HeritageNetwork/Regional_SDM/blob/5512e53d593143ede903aebf1a47ff74ef2d19fc/user_run_SDM.R#L20

@dnbucklin all of the "nm_" objects in `user_run_SDM.R` contain the extension for the filename, with the exception of the above quoted line (`nm_presfile`). Any reason why this one shouldn't also have '.shp' appended too?  Seems inconsistent to me.   As in, like this:

nm_presFile <- here("_data", "occurrence", paste0(model_species, ".shp"))

**Comment by dnbucklin** [comment]
Agreed, we should be consistent and always include the extensions in user_run_SDM. I think that was a legacy of `readOGR` which did not want the extension (but we always stripped the extension so it will work either way).

Just fixed in 1d002fb2

**Comment by tghoward** [comment]
Nice.
