### ISSUE TITLE
background samples

### ISSUE THREAD

**Issue by dnbucklin** [HeritageNetwork/Regional_SDM#27]
Should we change how we generate and store background points/reaches tables, given we're using ranges to define model domains? A couple questions related to this:

Is it a necessary (or just a good idea) to use the same background points for every species? Alternatively we could generate them on-the-fly in step 1. This would allow us to vary the density/number of background points to use by species, if desired.

We could also attribute background points (extract values from EVs) within the model process. I think this is a more flexible way to go and shouldn't add much extra time, given we're already loading the data to attribute presence points.

Should we alter the exclusion distance for background points? It's only 30m now - it could be at least increased to the raster resolution.

**Comment by ChristopherTracey** [comment]
Initially when we started the Reg5/SALLC projects, we were attributing the background points ourselves for each model run and it was taking a _significantly long time_. At some point Tim decided to attribute a master set of points to distribute to everyone and rewrote the script to reference this file as it is now. 

It may be something that's worthwhile as we may be modeling smaller areas than the Reg5 area and, as you mention, the number could be varied. However, we're likely going to be pressed for time and we may just want to go for the pre-attributed version.

I would support the exclusion distance being the same as the raster resolution.

**Comment by dnbucklin** [comment]
Good to know. I guess this could use some testing with the actual ranges and EVs we're going to be using.

If we do make a master background layer, we'd want to make sure it's at a sufficient density so that we get enough points for the small-ranged species. I've had the case where there were not enough background samples available in a fixed set to match the number of presence samples (for large presence polygons).

**Comment by ChristopherTracey** [comment]
Maybe that's the answer. Attribute a really dense background point later and then have the model extract a sample of the points within the range.

**Comment by dnbucklin** [comment]
Agreed, that likely would be a much faster approach. I think storing these attributed background datasets in an SQLite database could also save us some time as well. I can re-work our preprocessing scripts to do this.

Regarding variable names - we have columns `fullName`, `gridName` in our lkpEnvVars table - I could add a `fileName` column here to store original .tif filenames and we could continue to use `gridName` for  internal/table column names.

**Comment by tghoward** [comment]
The background points do need to be spatial for subsetting and removing points close to presence points. What were you thinking for implementation?

Yes, please do add a fileName field. On my test DB I actually called it gridFileName, but I don't have a strong preference for what it's called.

**Comment by ChristopherTracey** [comment]
Although it doesn't bother me much, we use the gridName for the aquatic model as well, and it doesn't really describe the non-grid data that we're using. So, if we wanted to move that towards a more general name...

**Comment by dnbucklin** [comment]
I was thinking of storing either the WKT representation of the points, or the raw coordinates. `sf` can easily import/export these. I just tested loading 200K points into a `sf` object and it took about 5 seconds. We could also use a bounding box query to subset what we're pulling from the DB that would speed that up.

The other option would be to store them as spatial objects (e.g. [Spatialite](http://www.gaia-gis.it/gaia-sins/)). I'm not sure that's worth the extra package dependency in this case though.

**Comment by ChristopherTracey** [comment]
Interesting thoughts about a WKT representation. I like it.

I have a nearly functioning SQLite based EnvVar code working for the aquatic models. I have to just make the lkpEnvVars table.  It's super fast, even unindexed.   

Speaking of, rather than a bounding box, why not just added a HUC10 field to the table and we can subset by the HUC10's from the range maps?  This would make the the terrestrial and aquatic branches a little closer.

**Comment by tghoward** [comment]
I think that sounds great to use the WKT and read it with sf.  I'd say go for it.   

We use spatialite a lot here (works great with [Geopaparazzi](https://geopaparazzi.github.io/geopaparazzi/)), but I agree it probably isn't necessary here.

**Comment by tghoward** [comment]
The HUC10 subsetting is a good idea for model-range subsetting.

**Comment by dnbucklin** [comment]
That's a great idea with the HUC10 field for each point! Then we wouldn't need to do any spatial queries from the DB. Maybe we could even store the HUC12 so it's completely flexible and matches the aquatics?

So a minimal background table could really just be:

FID/[comid] | huc12 | wkt 
--- | --- | ---
1 |  "123456789012" | "POINT 1 1" 

We could put the variables in here, or separate table might be cleaner with the FID linking them. Does that work with what you're doing with aquatics Chris?

**Comment by ChristopherTracey** [comment]
Yeah, let's store the HUC12 so its completely flexible--great idea!

My table is currently like this:
comid | huc12 | Variable1 | Variable2 
--- | --- | --- | ---
987654 |  "123456789012" | "somevalue"  | "somevalue"

I would be willing to moved to a linked table.  I could even put the WKT for the flowline in your proposed wkt field.

**Comment by tghoward** [comment]
But we'd still need the spatial query to remove points near presence points?

**Comment by dnbucklin** [comment]
I think we could continue to do that with `sf` in R as it's already coded in script 1. The original subset is just to avoid loading the full national dataset into R for every model run.

**Comment by tghoward** [comment]
Excellent. Good point.

**Comment by ChristopherTracey** [comment]
Let me get the aquatics branch updated and we can build off of that code. Should be done later today.

**Comment by dnbucklin** [comment]
I just added a terrestrial-only PR (#28) for some new methods since they're mostly independent from aquatics, but I did add was the `fileName` column to lkpEnvVars[Aqua]. 

The `raster::extract` function seems like it can be inconsistent, sometimes it's extremely slow, but other times it's (somewhat) faster. 

A couple questions on this: Do we want to do something more sophisticated with our sampling? It's just using base `sf:st_sample` now, which only offers random sampling (but we could stratify by polygons). Another thing to consider: should we remove duplicate points in the same raster cell?

**Comment by dnbucklin** [comment]
@ChristopherTracey I'm working through your latest PR to aquatics using the EV DB. I have couple suggestions on how to move forward: 

- I think we can re-use `nm_envVars` to store the path the to DB and table stroring the EVs.
- for now `nm_allflowlines` is a shapefile but we could make it a database table as well, storing the WKT representations of the exact same set of flowlines in `nm_envVars`. 

I'm working on the above changes and will add a PR soon. In the end we should be able to merge these into one argument that's common to both terrestrial/aquatic.


To that end, if you could set up your background/EV db with these tables/column names, as I've proposed for terrestrial in #28, I think that would be helpful:
**background_reaches** : [columns: comid, huc12, wkt]
**background_reaches_att**: [columns: comid, var1, var2, ...]

The 'background_reaches' in the example is a code name you'd provide for `nm_envVars` and you could store several of these pairs of background tables in the master database (I'm proposing to store that at `_data\env_vars\tabular\background.sqlite`). 

This seem ok to you?

**Comment by ChristopherTracey** [comment]
Yes. This seems like a good path forward and I like how it brings the terrestrial/aquatic branches closer together.

I've made this table changes the bg/EV db.  Good call on pull the huc12 out of the EV table, as it was bothering me there.  Do you want me to generate WKTs for the all the flowlines?

**Comment by dnbucklin** [comment]
I think so, that's really the last piece in moving away from a shapefile. I used `sf` to do that with the points. If you load in all the reaches into object `sf` it should just be a `wkt <- st_as_text(sf$geometry)` call (not sure how that will work with the full dataset!)

One other thing: I'm storing the projection in that database as the 'proj4string' in a `lkpCRS` table:

![image](https://user-images.githubusercontent.com/12412492/48147937-92220c00-e286-11e8-8258-d6448ca8958d.png)

You can get the proj4string with `st_crs(sf)$proj4string`.

**Comment by ChristopherTracey** [comment]
Cool. I'll start work on that. Should I also build a wkt set for the NHD_Area?

**Comment by dnbucklin** [comment]
Oh that reminds me, for aquatics we'd want [`wacomid`,`strord`] in the geometry table as well, if we want to use those in plotting. 

But I wouldn't be against dropping the NHDArea and `wacomid` from usage. That was a derived layer I created combining NHDWaterbody and NHDArea features. If we do keep it I'd probably leave it as a shapefile, since the WKT could get crazy for those polygons.

**Comment by ChristopherTracey** [comment]
Ok, in the seamless NHD, those fields have been renamed to [`WBAREACOMI`,`StreamOrde`]. I can be convinced that we potentially drop them from usage. I do like how the maps look, though.

**Comment by dnbucklin** [comment]
Hmm, I just found out you can query a shapefile directly in `st_read` with sf!! I had assumed that was just for databases, but I guess not:

```
bla <- st_read("VA_nhdarea_wb.shp", query = "SELECT comid, ftype FROM \"VA_nhdarea_wb\" where ftype = 'StreamRiver'")
```

So we could just stick with the area as a shapefile and query what we bring in. 

Now I'm questioning if we even need the Sqlite background database...

**Comment by ChristopherTracey** [comment]
That is neat.  However, we're dealing with huge file sizes here, the CONUSwide flowline layer is 2.7 million features and probably a few gigabytes in size (its an a geodatabase currently).  How efficient would it be to query that as a shp?  It seems like if we can pull the subsets from sqlite and build the flowlines from there, it might be faster.

**Comment by dnbucklin** [comment]
I would expect sqlite to be more efficient. And I definitely like the format better than shapefiles, for structuring these background datasets at least, if storing the wkt representation of the 2.7M lines isn't problematic(?) On my small test dataset it wasn't an issue.

But it would be nice to keep the ancillary datasets as shapefiles, especially since `st_read` can query. For the NHD area/waterbodies dataset I think we'd only really need a shapefile with the `WBAREACOMI` attribute, it seems.

**Comment by ChristopherTracey** [comment]
The wkt creation for the flowlines has been running for four hours and still isn't finished. Hopefully tomorrow...

**Comment by ChristopherTracey** [comment]
Working on getting this running with the full background dataset.  Some notes:

The background_reaches database needed indexes created for performance reasons:
`CREATE INDEX ind_comid ON background_reaches (COMID);`
and
`CREATE INDEX ind_huc12 ON background_reaches (HUC_12);`

I restored the `names(shapef) <- tolower(names(shapef))` on line 115 of script 1 and added similar code downstream of that as the sqlite has these fields capitalized.

The nationwide NHD flowline dataset is in geographic coordinates and I had to add a few `st_zm` calls to get `st_intersects` to run as it doesn't like z/m-coordinates.

**Comment by ChristopherTracey** [comment]
@dnbucklin any clue why the script 3 would fail early in the code at a rf call?

> Error in if (n == 0) stop("data (x) has 0 rows") : 
>   argument is of length zero
> Called from: randomForest.default(x, y, mtry = mtryStart, ntree = ntreeTry, 
>     keep.forest = FALSE, ...)

**Comment by dnbucklin** [comment]
Since the data has zero rows, perhaps there are some NA values in the predictors or any of the other columns (`"sname","eo_id_st","pres","stratum","comid", "huc12"`), and the `complete.cases` are dropping everything...

Can I merge #32 ? I think if you test the code with those revisions it would be helpful.

**Comment by ChristopherTracey** [comment]
Regarding #32, sure. However, I'm working off of dnbucklin/Regional_SDM

**Comment by ChristopherTracey** [comment]
The same issue as reported in #30 has reappeared. I'll figure out what the difference is.

**Comment by ChristopherTracey** [comment]
As just noted in #30,  most of the problems centered around case issues in the EnvVar db table.  @dnbucklin, did your test version of the sqlite have lowercase column names?

Added a bunch of `toLower()`'s and some other cleanup code and it appears to be running from start to finish now.

**Comment by ChristopherTracey** [comment]
Additionally, we were getting a `comid.1` column during the join that forms `colList`.  Trimmed that form the table.

**Comment by dnbucklin** [comment]
I was using my original statewide dataset for testing with this new background database, so yes the names were all lowercase. Not that they need to be lowercase, but it would be nice if we can avoid needing `toLower` for the env var names. With the new approach it should only be a matter of making sure the background database column names match up one-to-one with `lkpEnvVarsAqua.gridName`.

I'm trying to see how `comid.1` ended up in `colList`: is `comid` listed in `lkpEnvVarsAqua.gridName`? I'm not sure how else that could happen.

**Comment by tghoward** [comment]
> Hmm, I just found out you can query a shapefile directly in `st_read` with sf!! I had assumed that was just for databases, but I guess not:
> 
> ```
> bla <- st_read("VA_nhdarea_wb.shp", query = "SELECT comid, ftype FROM \"VA_nhdarea_wb\" where ftype = 'StreamRiver'")
> ```
> So we could just stick with the area as a shapefile and query what we bring in.

Just tried this for the HUC10 layer: reading the entire CONUS then subsetting or reading only the HUCs needed for the range definition. Using the query wins by a long shot:

```
> mb
Unit: seconds
          expr      min       lq     mean   median       uq      max neval
 readEntireHUC 7.166272 7.239477 7.461027 7.375594 7.537429 8.097972    10
 readwithQuery 1.216098 3.317769 3.152450 3.368434 3.388944 3.431777    10
```

excellent ...

**Comment by dnbucklin** [comment]
> Additionally, we were getting a `comid.1` column during the join that forms `colList`. Trimmed that form the table.

@ChristopherTracey I removed this change since in 6642a1c0 since I'm pretty sure the `comid.1` was there because `comid` is in your `lkpEnvVarsAqua.gridName` column. Also cleaned up some `run_SDM` internal stuff.

**Comment by dnbucklin** [comment]
Another change I made in 6642a1c was to limit the number of background samples to a maximum of 10,000 (it will be less than this in some cases). Other options could be to use some proportion of the total number of reaches in the model domain, or a multiple of the presence reaches. 

But given our RF sampling scheme I'm not sure it matters much - any thoughts on this? This also could be relevant to terrestrial background point sampling.

**Comment by tghoward** [comment]
I think we are good here. Closing for now.
