### ISSUE TITLE
clusterR fails with extent argument

### ISSUE THREAD

**Issue by tghoward** [HeritageNetwork/Regional_SDM#31]
In script 4, if I set an extent and then try to use it in the call like this:
```
 outRas <- clusterR(envStack, predict, args = list(model=rf.full, type = "prob", index = 2, 
                                                      ext = hucExtent, filename = fileNm),  verbose = TRUE)
```
it fails, while the single core call works fine
```
    outRas <- predict(object=envStack, model=rf.full, type = "prob", index=2, ext = hucExtent,
                      filename=fileNm, format = "GTiff", overwrite=TRUE)
```

Does anyone know any other way to get this to work? Is there any chance we can leverage Microsoft R Open here?

Tim

**Comment by dnbucklin** [comment]
This from `?clusterR` seems to indicate the problem:

> This function only works with functions that have a Raster* object as first argument and that operate on a cell by cell basis (i.e., there is no effect of neigboring cells) and _**return an object with the same number of cells as the input raster object**_

The cluster does internal cropping of the original raster prior to running which would conflict with the `ext` setting.

It seems the two options around this would be:
- `crop(envStack, hucExent)` prior to `predict`
or
- `crop(outRas, hucExtent)` after `predict`. With this you'd want to save the raster later, not during the `predict`. 

I'd guess the latter option is faster but I'd test it for a small extent first...

**Comment by tghoward** [comment]
Hmm, no, I don't think predicting at the full extent will be time productive. We really need to avoid scanning every cell for the entire CONUS to make a predict for just a few square km, for example. 

I've tried cropping the first layer of the stack (to create a sea of NA where we don't want to do the predict), which might make scanning through the entire CONUS faster, but it got hung up as well. 

A single core predict for a small area using a full CONUS raster stack and including the `ext` argument was fast. Which is very heartening. 

I'll keep exploring.   (after all day meetings today!)

**Comment by tghoward** [comment]
This is pretty funny. Using Revolution R's (or, now MRO's) MKL multi-threading does not give improvements for this kind of work:
```
> mb <- microbenchmark(
+   "manythreads"={
+                 setMKLthreads(32)
+                 outRas <- predict(object=envStack, model=rf.full, type = "prob", index=2, ext = hucExtent,
+                                   filename=fileNm, format = "GTiff", overwrite=TRUE)
+                 }, 
+ "onethread"={
+           setMKLthreads(1)
+           outRas <- predict(object=envStack, model=rf.full, type = "prob", index=2, ext = hucExtent,
+                             filename=fileNm, format = "GTiff", overwrite=TRUE)
+           }, times = 5)
> mb
Unit: seconds
        expr      min       lq     mean   median       uq       max neval
 manythreads 97.00019 97.96734 99.28871 98.28100 98.63681 104.55819     5
   onethread 96.72703 97.20569 97.72455 97.84823 98.05045  98.79135     5
```

so that got me nowhere.   Going to explore `stars`  next

https://cran.r-project.org/web/packages/stars/index.html

**Comment by ChristopherTracey** [comment]
You could say it was the opposite of an improvement...

**Comment by dnbucklin** [comment]
We could emulate a database approach and use a tiling scheme for our big rasters. Then we'd only import the tiles that intersect the hucExtent. 

You could then run the standard cluster predict on each tile's stack in a loop, mosaic the outputs if there's more than one, and mask the output to the actual HUC boundaries.

**Comment by tghoward** [comment]
Good idea on the tiling scheme, but probably too time intensive setting up. We are having plenty of difficulties getting the full conus rasters as it is. Sticking with the full rasters is probably where we are stuck giving the time frame and what we've got.

**Comment by dnbucklin** [comment]
I checked out `stars` for the first time today. It looks promising.

**Comment by tghoward** [comment]
Unfortunately, using `read_stars` on the full CONUS misbehaves, because it wants to load into ram
```
> envStack <- read_stars(fullL, along = 3)
Error: cannot allocate vector of size 160.5 Gb
```
I spent some time with RasterIO, which I agree looks very cool, but then realized that getting cell counts from coordinate locations is not straightforward.

I have a solution using proxy is true, that will work for the smaller predicts where stack for the entire predict area can be read into ram. It is similar or a little bit faster than using the classic approach with setting 'ext'.   I like your `st_apply` use and will try to work that in.

**Comment by dnbucklin** [comment]
@tghoward You may already be on this, but the `CLUSTER` argument of `st_apply` seems to help a lot with processing time. On the little test stack, it's ~5x faster than a cluster predict with `raster`. This is what I did:

```
library(snow)
envStack <- read_stars(fullL, proxy = T)

cl <- makeCluster(11, type = "SOCK") 
clusterEvalQ(cl, library(randomForest)) # load randomForest into clusters
clusterExport(cl, "rf.full") # load model into clusters

ev <- c(st_as_stars(envStack)) # COULD SUBSET HERE using envStack[bb]
pred1 <- st_apply(ev, 1:2, FUN = function(x) {predict(rf.full, x, type = "prob")}, CLUSTER = cl)
out <- as(slice.stars(pred1, along = 1, index = 2), "Raster")
```

It seems we could loop the process in last three lines process over subsets of the proxy `envStack`, just loading into memory defined subsets (`ev`), like is done [here](https://cran.r-project.org/web/packages/stars/vignettes/proxy.html#select-an-area). 

A problem with this `st_apply` approach is it fails if there are any NA values in the rasters, because it's using the base `predict` function. But there may be a simple solution to that I'm not thinking of (?)

**Comment by tghoward** [comment]
@dnbucklin I'm hoping for smaller ranges we'll be able to load the subsetted stack into ram. Still working on it though. If you think you can get somewhere predicting in our own defined chunks, feel free to try to figure it out. 

Using clusters looks great.

**Comment by tghoward** [comment]
Unfortunately, stars doesn't seem mature enough to attempt those approaches you are working out -- e.g. even this simple call `envStack <- read_stars(fullL, proxy = T)` errors out with the production rasters (while reading a single raster from the list works:
```
> envStack <- read_stars(fullL, proxy = TRUE)
Error in path.expand(path) : invalid 'path' argument
> (x <- read_stars(fullL[[1]], proxy = TRUE))
stars_proxy object with 1 attribute in file:
$`E:\\mobi_repo_tgh\\Regional_SDM\\_data\\env_vars\\raster\\beersx1000.tif`
[1] "beersx1000.tif"

dimension(s):
  from     to   offset delta                       refsys point values    
x    1 199987 -2950605    30 +proj=aea +lat_1=29.5 +la... FALSE   NULL [x]
y    1 107729  3340545   -30 +proj=aea +lat_1=29.5 +la... FALSE   NULL [y]
```
I've come up with a few approaches, of which one that combines different components of raster and stars seems the fastest on my test set.  Basically it entails reading the raster subsets with stars, but then putting them in a raster stack and running the predict on the stack:

```
setwd(loc_envVars)
rasRasList <- vector("list", length(fullL))
for(i in 1:length(fullL)){
  x <- read_stars(fullL[[i]], proxy = TRUE)
  xsub <- x[hucRange]
  rasRasList[[i]] <- as(st_as_stars(xsub), "Raster")
}
stk2 <- stack(unlist(rasRasList))
names(stk2) <- names(fullL)
stk2.m <- mask(envStk.c, hucRange)
setwd(paste0(loc_model, "/", model_species,"/outputs"))
fileNm <- paste0("model_predictions/", model_run_name,"_stars.tif")
outRas <- predict(object=stk2.m, model=rf.full, type = "prob", index=2,
                  filename=fileNm, format = "GTiff", overwrite=TRUE)
```

I don't know how it will behave with larger predict areas.  I wonder if there's a way I can get you these large CONUS test rasters?

**Comment by tghoward** [comment]
@dnbucklin  see PR: https://github.com/HeritageNetwork/Regional_SDM/pull/35

for the four different approaches that I got working. I created this PR just to you can get the code.

**Comment by dnbucklin** [comment]
I was starting to think the same thing re: `stars`; I agree your solution using `stars` just for the subsetting is the best we can do with the package as it is now.

Unfortunately it seems this will fail when `st_as_stars(xsub)` gets too large for memory. That's where I think we'd need to either to load/process the data in chunks for the prediction step, or (alternatively) crop/mask the rasters ahead of time (e.g. w/ gdal).

I've looked into these and have some code I could push for testing. It would be great to get access to the CONUS rasters too.

**Comment by dnbucklin** [comment]
@tghoward I may have had a little breakthrough on this! Since `stars` seems to have a lot of issues I went another route, which is just creating crop/masked EV raster copies for each species during the run (within script 2). I did this with `gdal` system calls, which are much faster than doing those processes with `raster`. Then I figured out I could cluster call these `gdal` calls, which speed the process up a lot more (I'd say as many times as you have clusters).

I just pushed a branch here (https://github.com/dnbucklin/Regional_SDM/tree/feature_croprast) which is up-to-date with the latest terrestrial edits - would be great it you could test it.

You'll need to be able to call gdal from command line from R, you can test that with:
```
system("gdalinfo --version")
```
> GDAL 2.2.1, released 2017/06/23

**Comment by dnbucklin** [comment]
If you're not seeing the GDAL version you probably need to set your Windows environmental variables (see [here](https://gisforthought.com/setting-up-your-gdal-and-ogr-environmental-variables/) ) so it will find the function.

**Comment by tghoward** [comment]
@dnbucklin excited to try it. Stuck at the beginning, however. OSGeo4W64 is not installed similarly to the link you provided. I'm tracking it down.

**Comment by tghoward** [comment]
info when loading `rgdal`  is as follows
```
> library(rgdal)
Loading required package: sp
rgdal: version: 1.3-3, (SVN revision 759)
 Geospatial Data Abstraction Library extensions to R successfully loaded
 Loaded GDAL runtime: GDAL 2.2.3, released 2017/11/20
 Path to GDAL shared files: C:/Users/Tim/Documents/R/win-library/3.5/rgdal/gdal
 GDAL binary built with GEOS: TRUE 
 Loaded PROJ.4 runtime: Rel. 4.9.3, 15 August 2016, [PJ_VERSION: 493]
 Path to PROJ.4 shared files: C:/Users/Tim/Documents/R/win-library/3.5/rgdal/proj
 Linking to sp version: 1.3-1 
> 
```

**Comment by tghoward** [comment]
Nope, I'm pretty sure it isn't installed. there *is* an Anaconda install, but it is throwing errors:
```
C:\Anaconda\Lib\site-packages\osgeo>gdalwarp --version
ERROR 1: Can't load requested DLL: C:\Anaconda\Lib\site-packages\osgeo\gdalplugins\ogr_FileGDB.dll
126: The specified module could not be found.

ERROR 1: Can't load requested DLL: C:\Anaconda\Lib\site-packages\osgeo\gdalplugins\ogr_FileGDB.dll
126: The specified module could not be found.

GDAL 2.2.3, released 2017/11/20
```

**Comment by tghoward** [comment]
I think this is great, but since I can't test right now .... a question on the approach:  If we are dropping many, possibly dozens of, rasters from the stack in script 3, those rasters we drop don't need to be in the final predict stack.  What do you think the benefit is to having a cropped raster stack for attributing in script 2? And does that overweigh the time loss for cropping those rasters that won't get used in the predict?

**Comment by dnbucklin** [comment]
> OSGeo4W64 is not installed similarly to the link you provided. I'm tracking it down.

I did install this via the 64-bit installer from [here](https://trac.osgeo.org/osgeo4w/); I think each different program (ArcGIS, R, etc) generally use their own gdal installation. 

OSGeo4w is generally used to install QGIS, but you when you use express desktop install you can choose which components you want to install (I just went with GDAL and GRASS). I just re-installed today and it's working as expected.

**Comment by tghoward** [comment]
Ok. I've put in a request.

**Comment by dnbucklin** [comment]
> What do you think the benefit is to having a cropped raster stack for attributing in script 2? And does that overweigh the time loss for cropping those rasters that won't get used in the predict?

Good point - I'm guessing that the time saved on the point attribution probably isn't worth it in most cases, since a lot of predictors will get dropped. I'll test it out. Also, this would save hard drive space.

**Comment by dnbucklin** [comment]
On my test datasets, it was definitely faster to crop/mask the rasters in step 4, since there were significantly less files to process (especially since I'm using a number of temporal EVs). I've updated the scripts to do that and just opened the PR on the terrestrial branch #38 . I

Because of how fast hard drive space would be eaten up if we save these rasters, I set the temporary rasters folder `species\[species_code]\inputs\temp_rasts` to be deleted right after the prediction raster is created.

**Comment by tghoward** [comment]
Ok good.  Mobiprep also has a C: drive that is very restricted in size, so I've already re-defined all R temp files to write to a different drive, using a .profile file in `C:\Users\Tim\Documents\R`. I'll have to make a note of that for all users.

**Comment by dnbucklin** [comment]
Good to know - the way it's coded, at line 27 in 'helper/crop_mask_rast.R', it's fixed to a location inside `loc_model`.

Another option could be to store them where the original rasters are located (`loc_envVars`), e.g. create a folder at `dirname(loc_envVars)`.

**Comment by tghoward** [comment]
Great solution, AFAICT, at least for my test set. Not thrilled about having to crop the raster stack for every single species, but it seems like there may be no silver bullet here.
