### ISSUE TITLE
'repo_head' not found

### ISSUE THREAD

**Issue by ChristopherTracey** [HeritageNetwork/Regional_SDM#33]
`repo_head` isn't being found when it try to write to the modelrun_meta_data table.

**Comment by dnbucklin** [comment]
Does this work? 
```
repo <- git2r::repository()
repo_head <- git2r::last_commit(repo)$sha
repo_head
```
[1] "99fe7670d20a38b0f6db06787c452f4bc0e11d7e"

**Comment by dnbucklin** [comment]
Or if you mean your sqlite database table `tblModelResults`; `repo_head` is a recently added column there.

**Comment by ChristopherTracey** [comment]
Yes, that bit of code works, and it works if you run that section of code in run_sdm.r manually.

I added `repo_head` to `tblModelResults`, so it shouldn't be that.

**Comment by dnbucklin** [comment]
Although I couldn't replicate this error, I just added a couple commits to the dnbucklin fork to clean up the modelrun_meta_data stuff, and hopefully a fresh model run with those scripts should fix it.

Also added back in the aquatic areas plotting, which needs the `wacomid` column in your background reaches table (table with the wkt) to work.

**Comment by dnbucklin** [comment]
Assuming this is fixed but re-open if not...
