### ISSUE TITLE
deleting ".tex",".log",".aux",".out" files if metadata pdf is successfully created

### ISSUE THREAD

**Issue by ChristopherTracey** [HeritageNetwork/Regional_SDM#44]
I couldn't see a good reason to keep all those files if the pdf is successfully created, especially since we we're dealing with thousands of files in the MoBI project.  So I wrote some code to delete them if the pdf is successfully created. It its not, they are kept.

It's in #43, but please push to master if you think its useful

**Comment by dnbucklin** [comment]
I have used the .tex files after the fact to edit/re-build PDFs in some cases; it might be worth keeping that file around just in case.

**Comment by ChristopherTracey** [comment]
That's a good point. We can pull that extension out of the delete list.

**Comment by dnbucklin** [comment]
added to master/terrestrial c6c94255
