### ISSUE TITLE
presence file names

### ISSUE THREAD

**Issue by ChristopherTracey** [HeritageNetwork/Regional_SDM#45]
Maybe this should be included in #14, but what is our input file naming convention?  Are we planning on using the CuteCode or EGT?

**Comment by dnbucklin** [comment]
I'd vote for CuteCode for all file and folder naming, but could be convinced otherwise!

**Comment by tghoward** [comment]
I agree to go with CuteCode.

**Comment by ChristopherTracey** [comment]
CuteCode it is!
