### ISSUE TITLE
map sources to spp?

### ISSUE THREAD

**Issue by tghoward** [HeritageNetwork/Regional_SDM#48]
@ChristopherTracey any thoughts how we'll use (or if we'll need to use) the Data Sources table (lkpDataSources) and the map to species table (mapDataSourcesToSpp) in the tracking DB in this project? If you count the mjd as one source, we have only a few sources, but it will vary by species. How might we get these tables filled?  Does the mjd count as one source?

**Comment by ChristopherTracey** [comment]
I think we should be citing our data sources. As far as I know, we have the following sources:
- MJD
- GBIF
- BISON
- iNaturalist
All of these should be cited (I can work up citations for the outside data).  One question is whether the MT, WY, AR, etc data counts as part of the MJD and whether those programs get separate citations?

As far as filling the tables, shouldn't we be able generate an concatenate the info from the GIS data? It may take a script, but it should be pretty simple.  And useful for the future.

**Comment by ChristopherTracey** [comment]
Regan is talking to Shara about the MJD questions.

**Comment by tghoward** [comment]
I'll put out there that it might make sense to cite the national data (MJD, BISON, iNat, GBIF), in _all_ metadata output pdfs, because even if we ended up not using those data, we certainly did review them in the context of each species. So, for example, if we decide we have enough MJD data and don't use the BIG data, we still looked at the BIG data assessed its value, etc. Vice versa with MJD data: say we only had X and H level EOs ... we still had to look at it and make that decision. 

Other, more local datasets, should be tagged to taxa, however, and we need to come up with a way to do that.
