### ISSUE TITLE
Aquatic - error in HUC subset if project area covers multiple HUC02s

### ISSUE THREAD

**Issue by ChristopherTracey** [HeritageNetwork/Regional_SDM#49]
If the selected project area spans multiple HUC2's this error appears.

> Using huc_level of 0...
> Error in paste(HUCsubset, collapse = "','") : 
>   object 'HUCsubset' not found

**Comment by ChristopherTracey** [comment]
Seems to be able to fix if the HUC level is never set to zero, and use two instead.  This will generate a vector that we can subset using the %in% operator dowstream.

```
  } else {
    huc_level <- 2
 } 
```
Consider moving this to HUC4 and never dropping down to HUC2.

**Comment by dnbucklin** [comment]
I made edits in b5847e4 on this. No functional changes for this project (since we're auto-calculating `huc_level`), but it allows to specify `huc_level = 0` in `run_SDM` without error; this would run a model using all background reaches.
