### ISSUE TITLE
Incorporate rubric into metadata

### ISSUE THREAD

**Issue by ChristopherTracey** [HeritageNetwork/Regional_SDM#51]
per Regan's request

**Comment by ChristopherTracey** [comment]
@tghoward, I've been thinking about this for a few days now, and here are some thoughts:

1. We create a new section on the metadata document called "_Model Use_" or perhaps something a little more snappy.  This section has a short preamble about intended use (based off the Safaer et al paper).
2. In that section, we create a rubric table for that species. We probably can't fit the same exact layout as in the paper, but we could design something similar. Each attribute could be color coded (and text for b&w printers) with problematic, acceptable, or ideal.
3. We create a new table in SDM_lookupAndTracking.sqlite that stores the information. It seems like a lot of this can be pre-populated (eg. Heritage data seems like it should almost always score as _Ideal_ for 'presence data quality') and some of the predictors/methods seem like they will be the same.  For those that we may need to update, see the next item.
4. Created a new script (eg. `4d_ModelUseEval.r`) or potentially repurpose `4c_additionalMetadataComments.r` to insert and update attribute scores.  We should probably look at the 'Model Review' attribute and see how we can document that in the metadata.

How does this seem for a start?  Did I miss anything big?

**Comment by ReganSmyth** [comment]
I like it. A few thoughts:

1a. Maybe call it "Model Evaluation and Intended Use"
1b. I can take a stab at drafting the preamble
2. Whatever we can design to roughly match the paper would be great, but understand there might be constraints in format. Let's try to at least keep the language consistent and have entries for as many of the Table 1 rows as we can. Seems to me that for most MoBI models, the table entries would be nearly identical to each other.
3.  I'd actually argue that the MoBI locality data falls in problematic the problematic range for many (most?) species, since we know we are not thoroughly vetting and supplementing to the degree we'd like for "decision-quality" models. We should make sure the table reflects the differences between MoBI and "decision-quality" models, as it can serve as an important tool for communicating how we'd like to make those models better. Reviewing the table from this perspective would be helpful.
4. Totally defer to you there
5. As for content/rankings: would it make sense for a small group of us to go through the table together and on problematic/acceptable/ideal rankings or criteria therefore and more generally what we want to capture?

(and hey, look at me using GitHub!!!)

**Comment by ChristopherTracey** [comment]
The the last question- Yes! Well done!

**Comment by ChristopherTracey** [comment]
Here's an attempt at a table for the metadata:
![img_4916](https://user-images.githubusercontent.com/8216371/50115898-b9b9ac00-0216-11e9-9b00-b27a50cdb516.jpg)
(apologies for the sloppiness)

I wasn't able to figure out how have the words and colors both reflected at the same time, but maybe we don't need them.

**Comment by ChristopherTracey** [comment]
1a. I'm fine with that.
1b. Great!  We're probably not looking for something very long here. A few sentences at most. We can cite the paper and point them towards it.
2. See above.
3. I see you're point, but I think we're still hitting most of what makes it ideal (accurate records, weighted on lower error) and we did minimize the acceptable issues (eg. taxomony). I think this should go down to acceptable if we're using GBIF/BISION data. This seems like part of the small group discussion through.

**Comment by tghoward** [comment]
This all looks good to me. I don't see why we can't mimic the table as it was presented in the ms?

**Comment by ChristopherTracey** [comment]
It's at N:\chris\huc12.7z, move to wherever you need it.

**Comment by tghoward** [comment]
for ^^ (above), see: https://github.com/HeritageNetwork/Regional_SDM/issues/62

**Comment by dnbucklin** [comment]
On (4) I'd suggest adding to script 4c, instead of creating a new script.

With the latest map edits, there is ~half page of empty space after the thresholds table in the metadata, since the map has its own page. Perhaps this table could fit there?

**Comment by ChristopherTracey** [comment]
I had just begun to enter code into 4c when you posted that. Strange...

I'll look into placing it there. Good point.

**Comment by ChristopherTracey** [comment]
So this is pretty cool. I got a rough prototype working. See below (I=Ideal, A=Acceptable, P=Problematic):

![image](https://user-images.githubusercontent.com/8216371/50188061-45ead280-02ee-11e9-9751-1b32f12bdc7f.png)
I still need to turn this into a fancy table or other datavis, so any suggestions on that would be welcome. 

@dnbucklin, I think we can fit this under the thresholds table and it works well there as it's also where the custom model comments live if they are present.

**Comment by ReganSmyth** [comment]
I like it -- though I do think we probably need to add some justification for our rankings. I see two options for doing this:

1. Include a sentence of justification in the metadata. Pros: information is right there for anyone who wants it. Cons: makes the metadata longer, more work to format and populate (some things would be the same for all models, some we might change - for instance based on the review ratings or what we know about quality of locality data based on sample size and/or Anne's survey)
2. Have a separate document available that explains the rankings MoBI-wide. Pros: easier to create, more flexibility in what is included. Cons: users need to go searching for something else to understand the models. 

I'm leaning towards the latter.

I'm going to work on the into blurb now. I still think we are being too generous in some of our rankings -- I think we need to make clear somewhere here that these are preliminary models, though maybe I can do it in the blurb. Stay tuned.

**Comment by ChristopherTracey** [comment]
Here's a new version that may answer some of your concerns:
![image](https://user-images.githubusercontent.com/8216371/50227316-7c1e6580-0373-11e9-9349-183df60c4d1d.png)
There's a note's column where we can write a short sentence explaining the ranks for each category, which is what the "EO data" represents. I chose to do this at the category (_is that even the right term?_) level as it could be more generalized than a single note for each Metric which could be 14 of them. I could change it though...  Anyway, that's where the justification can take place, at least in part.

Right now, when we run a model, there's a long vector in the model parameters that contain the default values and the notes for each species:
```
# default values for Model Use rubric
rubric_default = c("I","A","A","A","A","I","A","A","A","I","A","I","A","A","EO data",NA,NA,NA,NA)
```
One can edit the values here as needed. This then gets inserted into a new sqlite table called `tblRubric` which is keyed to `model_run_name`. I haven't written anything yet to alter the rankings after the model has run.  Still trying to figure out if we need to.

As far as the blurb, I think this should be kept general and not specific to MoBI. Especially as we use this modeling framework for non-MoBI projects.

**Comment by ReganSmyth** [comment]
Ugg - your reply addresses many of the things I had just written out in a response and was about to send! Starting over.

**New Notes Field**
I like it (though still think a separate doc with project specific details is a workable other option if it gets too unwieldy - text in brackets in the intro blurb would be if we go that route). I'm inclined to have a sentence for each row unfortunateley, as I think that's the level on info we'll want to provide. Curious what @tghoward thinks.

**Intro**
For the blurb - how about one general paragraph and one project-specific paragraph? I think the "intended use" is important to capture and will be project specific anyway. Having some info in there about what the MoBI models are and _are not_ intended for will allay some of my concerns on the specific rankings. 

_All SDMs are sensitive to data inputs and methodological choices. The following table represents scoring of modeling factors based on the model evaluation rubric presented in Sofaer et al 2019. [More information on the justification for each score is available (in supplementary materials?).]

Models developed for the MoBI project are intended to inform creation of a national map of biodiversity value, and we recommend additional refinement and review before these data are used for more targeted, species-specific decision making.  In particular, many MoBI models would benefit from greater consideration of species data and environmental predictor inputs, a more thorough review by species experts, and iteration to address comments received._

**Some comments on specific ratings and which ones I think might change by species**
Presence data: A (Variable A-I by species? If we have EO data from all states where the species is known to occur, I think we could call it ideal; else I think we need to acknowledge that it is acceptable at best – cooter is cautionary tale from a place where we even had data from all the states)

Performance: variable based on statistical results and perhaps also model review ranking?

Model review: A (I don’t think we can call our model review step ideal – just getting a thumbs up/thumbs down for each model will likely be a challenge, and our ability to make real refinements based on review feedback is going to be limited at best)

**Need for Groupings**
this was on my original list, but per usual, you're 3 steps ahead

**Comment by ChristopherTracey** [comment]
Regarding the 'project specific' blurb, that was something that I was already thinking about (_sorry!_) in association with the recommended citation.  It would be great if we could reference the models as part of a larger effort (eg. MoBI, Mid-Atlantic Butterflies, Region 5, etc).  There's also a question of funding acknowledgement, etc.

We have the ability to [insert additional comments](https://github.com/HeritageNetwork/Regional_SDM/blob/aquatic/4c_additionalMetadataComments.r) into the metadata. It was designed to make notes about different runs (I don't know how often its been used), but we could repurpose it as a project specific blurb.

**Comment by ReganSmyth** [comment]
Great. Though I still have quibbles with what shows up as green! 
Should we add writing up notes for each row and resolving ratings as a joint to do for after Jan 1?

**Comment by tghoward** [comment]
Nice lookin table!

**Comment by ChristopherTracey** [comment]
Rather than have this as a series of default values, maybe it would be better to store in `SDM_lookupAndTracking.sqlite` on a per species basis.

**Comment by tghoward** [comment]
@ChristopherTracey what's the status on all your metadata output work? Can I pull it into terrestrial? (Terrestrial branch might still be broken there in places)

**Comment by ChristopherTracey** [comment]
@tghoward, yes it’s should be ready to go. I think it still needs some refinement, but it should work for now.

**Comment by ChristopherTracey** [comment]
Added in a version of @ReganSmyth's MoBI blurb. It's a variable that can be set in `runSDM`.

**Comment by ChristopherTracey** [comment]
@tghoward I just pushed to the main aquatic branch in #80. We should move it to master, but I think I prefer that you do that (_I screwed it up last time..._).

**Comment by tghoward** [comment]
@ChristopherTracey  roger that. I'm in the middle of trying to get it all into terrestrial (the slow way, cherry picking wasn't working).   I'll see if i can also push it to master.

**Comment by tghoward** [comment]
Ok!  the rubric table is now in terrestrial and master. @ChristopherTracey if you could possibly make edits to master from now on, then we both should be able to pull from there. If it is much easier to do it in aquatic, I (hopefully) can cherry pick from now on -- i might have found a way around the `fatal: bad revision` issue I was having. 

closing this issue!

**Comment by ChristopherTracey** [comment]
@tghoward do you know how the following fields got into the db insert for the rubric in `5_createmetadata.r` on the HeritageNetwork:master?
   `notes_spdata, notes_envvar, notes_process, notes_products, notes_iterative`
These were from an older version of the rubric.  I don't see them in terrestrial or aquatic...

**Comment by tghoward** [comment]
Hmm, I don't see those in the current version, here online: https://github.com/HeritageNetwork/Regional_SDM/blame/master/sqlite/sqliteDBDump.sql

Is that where you mean?   I was going to use `blame` to figure out if it was mine (assumed it was), but I don't see those anymore? 
T

**Comment by ChristopherTracey** [comment]
It may have been just a missed stray from a previous PR.  I was syncing your edits from yesterday into aquatic and picked it up.  I'll delete it from master. No worries.

**Comment by ChristopherTracey** [comment]
I made some modifications to this tonight based on our conference call from a few weeks ago. Here's a quick summary:
- Replaced `tblRubric` with a new table called `tblSpeciesRubric` in the sqlite. This should be prepopulated with the all the model species including the EGT_ID and sp_code fields. The metric scores we agreed to on the call will be automatically populated (default values in the sqlite).
- Dropped the insert statement from `4c` as the data is populated in the database. The downside is that the rubric isn't associated with any particular model run.
- Script `5` now loads the database
- If the mean TSS value is less than 0.6, it downgrades the performance metric from a default of _Acceptable_ to _Interpret with Caution_.

We need to write the default notes. Anything else we should consider?

**Comment by tghoward** [comment]
@ChristopherTracey did you push these commits up to github?  By "these commits" I mean the new `tblSpeciesRubric` and other handling of rubric. I looked earlier but couldn't find.

**Comment by ChristopherTracey** [comment]
Tim, it's in the recently pulled #137. It needs to be integrated into Terrestrial.

**Comment by tghoward** [comment]
@ChristopherTracey excellent, thanks. Do you also have a table definition for the 

> a new table called `tblSpeciesRubric` in the sqlite.

? I can try to get it incorporated ....

**Comment by ChristopherTracey** [comment]
Ack! Sorry.

Try:
`CREATE TABLE "lkpSpeciesRubric" ( `EGT_ID` INTEGER, `sp_code` TEXT, `spdata_dataqual` TEXT DEFAULT 'I', `spdata_abs` TEXT DEFAULT 'A', `spdata_eval` TEXT DEFAULT 'A', `envvar_relevance` TEXT DEFAULT 'A', `envvar_align` TEXT DEFAULT 'A', `process_algo` TEXT DEFAULT 'A', `process_sens` TEXT DEFAULT 'A', `process_rigor` TEXT DEFAULT 'A', `process_perform` TEXT DEFAULT 'A', `process_review` TEXT DEFAULT 'C', `products_mapped` TEXT DEFAULT 'A', `products_support` TEXT DEFAULT 'I', `products_repo` TEXT DEFAULT 'I', `interative` TEXT DEFAULT 'C', `spdata_dataqualNotes` TEXT, `spdata_absNotes` TEXT, `spdata_evalNotes` TEXT DEFAULT 'Heritage data is great. ', `envvar_relevanceNotes` TEXT, `envvar_alignNotes` TEXT, `process_algoNotes` TEXT, `process_sensNotes` TEXT, `process_rigorNotes` TEXT, `process_performNotes` TEXT DEFAULT 'Do look at multiple metrics, do throw out models that really poor. ', `process_reviewNotes` TEXT, `products_mappedNotes` TEXT, `products_supportNotes` TEXT, `products_repoNotes` TEXT, `interativeNotes` TEXT )`

**Comment by ChristopherTracey** [comment]
I'm realizing that I never updated everything Anne and I wrote for the notes column last week. I'll get that done asap, but that table will work for testing.

**Comment by tghoward** [comment]
LOL, you snuck in these defaults: `Heritage data is great.`; `Do look at multiple metrics, do throw out models that really poor.`   hmmm...

**Comment by tghoward** [comment]
DB updated up here on github. #138 

Unfortunately, it (the sqlite db export) is over 50MB now, which github doesn't like. We'll need to come up with a solution to that.

**Comment by ChristopherTracey** [comment]
@tghoward, this is the default text that Anne and I came up with for the rubric to replace the fun ones I had inserted above.  Can you look them over and make sure that they are valid? Also I haven't figured out what we should write for _statistical rigor_--any ideas?

Metric | Group Rating | default description for rubric
-- | -- | --
Presence   data quality | Variable | **Ideal** - Heritage Network data   are vetted for accuracy and weighted for spatial representation.  **Acceptable** - Heritage Network data augmented with outside data which may or   may not be vetted for accuracy or weighted for spatial representation.          **Interpret with Caution** - Data taken from outside sources and may or may not   be vetted for accuracy or weighted for spatial representation.
Absence/Background data | Acceptable | Background points randomly placed throughout study area excluding species locations.
Evaluation data | Acceptable | Models are validated by jackknifing (i.e. leave-one-out).
Ecological and predictive relevance | Acceptable | Selection of predictor variables were based on previous modeling experience by the Natural Heritage Network. Time constraints of this project prevented making species specific selections.
Spatial and temporal alignment | Acceptable | Reasonable attempts to align predictor and presence data were made.
Algorithm choice | Acceptable+ | Random Forest is highly rated classification model that is well documented as suitable for modeling rare species.
Sensitivity | Acceptable- | Settings for Random Forest were adjusted to best model the species; however, different models/parameters were not tested within one model run.
Statistical rigor | Acceptable | ???
Performance | Acceptable for most; some will score poor based on TSS | **Acceptable** - Model TSS >=   0.6. Mapped model output is evaluated for ecological plausibility by expert   review. **Caution** - Model TSS < 0.6.  Mapped model output is evaluated for ecological plausibility by expert review.
Model review | Interpret with Caution (unless reviewed, and then its Acceptable | **Acceptable** - Model was reviewed   by regional, taxonomic experts. **Caution** - Model was not reviewed by regional, taxonomic experts.
Mapped products | Acceptable | Single calculated threshold selected for all final models to be integrated into MoBI.
Interpretation support products | Ideal | All standards met.
Reproducibility | Ideal- | All standards met.
Iterative | First version is red; turns yellow if reviewed/revised | **Acceptable** - Model revised.          **Caution** - Model not revised.

A few more questions:
- We rated some of these 'Acceptable+' or 'Acceptable-" rather than straight up Acceptable.  Do we want to keep these modifiers? [spoiler alert--I don't].
- We need to figure out how to track the Model Review and Iterative status so we can have the correct values coded. Any ideas?

**Comment by tghoward** [comment]
@ChristopherTracey I'm going to start working on this (metadata rubric comments). One problem is that adding all this text (which is good) to the sqlite will make it too big for github. Options:
1. use git large file storage for the sqlite (https://git-lfs.github.com/)
2. break it into multiple sqlite dbs
3. never export and write up this table (filled out) to github. So the base version of the DB doesn't have this table populated. 
4. export this table as csv (and perhaps other tables too) and track the csvs and emptier sqlite db on github. 

I think I'm leaning to option 3. Any opinions?

tim

**Comment by tghoward** [comment]
The two citations for _statistical rigor_ in the manuscript talk about spatial autocorrelation and collinearity. So we should address this way: "Collinearity of predictors recognized and addressed; presence points grouped to minimize sample bias and minimize spatial autocorrelation boost during validation; other assumptions recognized and considered."  (and it would get "Acceptable")

**Comment by tghoward** [comment]
I think we can call this issue finished!  see #142 for the final piece. 

some questions from earlier in this thread
> * We rated some of these 'Acceptable+' or 'Acceptable-" rather than straight up Acceptable.  Do we want to keep these modifiers? [spoiler alert--I don't].

I don't either, so right now implemented without the + or -

> * We need to figure out how to track the Model Review and Iterative status so we can have the correct values coded. Any ideas?

I've implemented it so the table in `SDM_lookuupAndTracking.sqlite` is updated based on an ODBC connection to `MoBI_Tracking_currentVersion.accdb`. 

@ChristopherTracey you need to prepopulate _lkpSpeciesRubric_ with the defaults. Running this SQL within `SDM_lookuupAndTracking.sqlite` will do it:
```
insert into lkpSpeciesRubric ( EGT_ID, sp_code )
select EGT_ID, sp_code
from lkpSpecies;
```

**Comment by ChristopherTracey** [comment]
Thanks for the `insert` -- made this easy!

**Comment by ChristopherTracey** [comment]
I believe I have the rubic working on the `aquatic` branch now!
