### ISSUE TITLE
Minimum scale for metadata map

### ISSUE THREAD

**Issue by ChristopherTracey** [HeritageNetwork/Regional_SDM#53]
State based? Other method?

**Comment by dnbucklin** [comment]
Not sure what you mean exactly - the extent is determined by the modeling range now, but are there cases you'd want to "zoom out" more?

**Comment by ChristopherTracey** [comment]
This was discussed on a recent MoBI call. There's some sensitivity about showing maps that are zoomed in too far to show detailed locations. It's not been decided to the actual scale we'll use.

**Comment by dnbucklin** [comment]
Got it. Related to this, I think we should probably drop the `nm_studyAreaExtent` file as an argument and automatically use the dissolved range features in its place. We could then use the `st_bbox` of the range to determine if we need to zoom out when we decide on the scale.

**Comment by ChristopherTracey** [comment]
I agree.

**Comment by tghoward** [comment]
done. Currently set to 100km across on either side of map. Might want to make that value larger. see #140
