### ISSUE TITLE
Change symbology on metadata map

### ISSUE THREAD

**Issue by ChristopherTracey** [HeritageNetwork/Regional_SDM#54]
1. Remove numbers
2. "low to high" scale

**Comment by dnbucklin** [comment]
@ChristopherTracey @tghoward Something simple like this work?

![image](https://user-images.githubusercontent.com/12412492/50104233-8287d280-01f7-11e9-9809-df749464398c.png)

If so I can push the changes for aquatic/terrestrial.

**Comment by tghoward** [comment]
That looks good. Even better would be "Low Habitat Suitability" and "High Habitat Suitability" or something like that to emphasize that we aren't mapping abundance, probability of presence, etc. 

We still might want to threshold out the lowest bins, IMHO. But that can wait for a later time.

**Comment by ChristopherTracey** [comment]
I think this works and agree with Tim on "Habitat Suitability". Awesome!

**Comment by dnbucklin** [comment]
See #58 . I set up the title and legend outside the mapping area:

![image](https://user-images.githubusercontent.com/12412492/50108899-59217380-0204-11e9-8e67-fc538843f806.png)

If it's good to merge I'll update aquatic/terrestrial branches.

**Comment by ChristopherTracey** [comment]
I like it. My only comment would be to have GNAME/GCOMNAME instread of just the common name.

**Comment by dnbucklin** [comment]
@ChristopherTracey Where would those (GNAME/GCOMNAME) get pulled from? Is that scientific_name and common_name from `lkpSpecies`?

**Comment by ChristopherTracey** [comment]
Yes, sorry. I was using the official BIOTICS terminology. Yes, those the are fields.  You should be able to pull them from ElementNames which is initially generated in Script3, but used in the metadata step.

**Comment by dnbucklin** [comment]
Closing as all branches are updated; maybe reference further map edits in #53
