### ISSUE TITLE
Is there any need to start including EGT-ID in the metadata?

### ISSUE THREAD

**Issue by ChristopherTracey** [HeritageNetwork/Regional_SDM#59]
@tghoward, we seem to be using EGT-ID a lot more than we used to.  Should it be included somewhere on the metadata?--perhaps next to `Species Code`.

**Comment by tghoward** [comment]
Yes, this is a good idea. Also, note that it might be easiest to swap out names in the input datasets with our 'master' names before starting the modeling process ... then you could use the scripts that depend on sci name?

**Comment by ChristopherTracey** [comment]
> then you could use the scripts that depend on sci name

This is what I was responding to. Since we're using point/line/polygon data from both EOs and outside sources, we built our aquatic prep scripts to depend less on the input fields, and just require a selected set of features. We tag the species name in the script and it builds the CuteCode from there.

Am I missing something?

**Comment by tghoward** [comment]
I don't know. If you are good; I'm good.

**Comment by tghoward** [comment]
done in #99
