### ISSUE TITLE
Automatically create a range map for aquatics based on selected HUCs

### ISSUE THREAD

**Issue by ChristopherTracey** [HeritageNetwork/Regional_SDM#64]
Started work on this yesterday:
- created a `range_huc12` table in background.sqlite that contains the HUC12 id and the WKT for the polygon
- in 4_predictModelToStudyArea.R, I added a step at the end to query this table, based on the selected HUCs, dissolve the HUCs into one polygon, and then convert to a shapefile.  It writes it to the 'model predictions folder, and names it using `model_run_name`.

Still need to integrate this into the map as the study area.

**Comment by ChristopherTracey** [comment]
Done. Removed `nm_StudyAreaExtent` from the aquatic branch, as its no longer needed.

![image](https://user-images.githubusercontent.com/8216371/50238764-463aaa80-038e-11e9-920f-35f2d9113f8d.png)

**Comment by dnbucklin** [comment]
Is this necessary to save it, if it's only used in the map(?) Seems it could be generated on the fly just in step 5.

Terrestrial already has methods in `helper/crop_rast_mask.r`, to pull from a huc10 shapefile:

```
db <- dbConnect(SQLite(),dbname=nm_db_file)
SQLquery <- paste0("SELECT huc10_id from lkpRange
                   inner join lkpSpecies on lkpRange.EGT_ID = lkpSpecies.EGT_ID
                   where lkpSpecies.sp_code = '", model_species, "';")
hucList <- dbGetQuery(db, statement = SQLquery)$huc10_id
dbDisconnect(db)
rm(db)

# now get that info spatially
nm_range <- nm_HUC_file
qry <- paste("SELECT * from HUC10 where HUC10 IN ('", paste(hucList, collapse = "', '"), "')", sep = "")
hucRange <- st_zm(st_read(nm_range, query = qry))
```

One option to have consistent aquatic/terrestrial methods here would be to calculate and write the `huc10`s values (that make up the aquatic range) to `lkpRange`.

**Comment by ChristopherTracey** [comment]
I did not know about that happening in Terrestrial. I was saving it, as I thought it could be useful as a standalone product. I had thought of just making it a temporary file.

**Comment by dnbucklin** [comment]
Sounds good, saving a shapefile probably is a good idea.

We could also adjust terrestrial methods to pull from the huc12 table you generated, if there are not concerns about differences between versions as discussed yesterday in #62.

**Comment by ChristopherTracey** [comment]
In order to make a layer of HUC10s that match the aquatic ranges for the model review tool, I've been trying to dissolve the by the HUC10 column using `sf` without success. @tghoward and @dnbucklin, do you have  any experience with this?

**Comment by dnbucklin** [comment]
If I'm understanding correctly I think `dplyr` is the way to go for something like this:
```
library(sf)
library(dplyr)

huc <- st_read("hucs.shp")
names(huc)

# use your huc10 field in group_by, geometry field in st_union
huc10 <- huc %>% group_by(HUC_10) %>% summarize(geometry = st_union(geometry))
```

**Comment by ChristopherTracey** [comment]
Thanks @dnbucklin! I had most of it together, but I was trying to use a different `group_by` approach. This works a lot better and cleaner than my draft code.

**Comment by ChristopherTracey** [comment]
Note that `dplyr` has to loaded before `sf` for this to work.
