### ISSUE TITLE
metadata: what does 'ability to find new sites' mean?

### ISSUE THREAD

**Issue by ChristopherTracey** [HeritageNetwork/Regional_SDM#81]
Hey @tghoward, this is a question I've had for a long time. What does the phrase 'ability to find new sites' mean under the thermometer on the metadata?

**Comment by tghoward** [comment]
Ha! funny, I was just thinking of that a day or so ago. That statement was the shortest shorthand in the plainest language I could come up with at the time for what the validation statistic means. Happy to change it to some other plain language.

**Comment by ChristopherTracey** [comment]
Ok. I don't have any better ideas at the moment, but we should probably brainstorm it out. It's the first thing everyone always asks when they look at the metadata document.

**Comment by ChristopherTracey** [comment]
Suggestion from Bruce Young: "Ability to predict known localities"

**Comment by ChristopherTracey** [comment]
@tghoward, if I was understanding what you were describing on the tech team call yesterday, I wonder if we could take a slightly different presentation method.  If a TSS of 0.8 means that there is an 80% chance that the predicts all the known localities. What if, instead of saying "ability to find new sites" or Bruce's suggestion, we say that there is "a 4 out 5 chance of predicting known sites"?

**Comment by tghoward** [comment]
The words "predicting known sites" implies internal validation, which this isn't. I wonder if we should keep it even more simple and just say "Validation success"

**Comment by ChristopherTracey** [comment]
Fair point, I was trying to build on your comments last week on the tech team call.  I do like the simple approach.

**Comment by tghoward** [comment]
replaced with 'validation success' in all branches
