### ISSUE TITLE
batch the wrapper?

### ISSUE THREAD

**Issue by tghoward** [HeritageNetwork/Regional_SDM#82]
@ChristopherTracey @dnbucklin , what's your setup to batch process `0_user_run_SDM.r`?  We definitely don't want to be manually changing the entries in that script and waiting for it to run before running a new spp.

**Comment by ChristopherTracey** [comment]
I haven’t thought that far ahead yet...

**Comment by dnbucklin** [comment]
I haven't used anything fancy yet, just query up a list of species codes from the database and wrap everything in a loop, e.g.:

```
# File: user_run_SDM.r
# Purpose: Run a new, full SDM model (all steps)

library(here)
library(RSQLite)
rm(list=ls())

# Modeling database
nm_db_file <- here("_data", "databases", "SDM_lookupAndTracking.sqlite")
db <- dbConnect(SQLite(), nm_db_file)
spp_list <- dbGetQuery(db , "SELECT sp_code s FROM lkpSpecies WHERE modtype = 'T' 
                       AND EGT_ID NOT IN (SELECT EGT_ID FROM tblModelResults) order by s limit 10;")$s
dbDisconnect(db)
rm(db)

for (spp in spp_list) {
model_species <- spp
...
# everything through run_SDM() call
...
}
```

A minimal version of this in a new script might make sense, with the `run_SDM()` wrapped in `try()` so it can just keep running.

**Comment by tghoward** [comment]
done 8b0b4f0899eb43c7cf86084e99f47bb7e13ba1e1
