### ISSUE TITLE
metadata: Table 1

### ISSUE THREAD

**Issue by ChristopherTracey** [HeritageNetwork/Regional_SDM#86]
Anne suggests that we change the order as follows:

- aquatic - It makes more sense to me to list PR reaches, Reach groups, then BG reaches.  
- terrestrial - Makes more sense to me to keep presence related numbers together. Suggest polys (capitalize the P), EOs, PR points, and BG points.

**Comment by tghoward** [comment]
done for terrestrial: https://github.com/HeritageNetwork/Regional_SDM/pull/94

**Comment by ChristopherTracey** [comment]
Done for aquatic as well: #100
