### ISSUE TITLE
metadata: italicize GNAME on map

### ISSUE THREAD

**Issue by ChristopherTracey** [HeritageNetwork/Regional_SDM#89]

**Comment by tghoward** [comment]
this is going to be hard. Might need a major rework. Perhaps when doing an overhaul with N arrrow, scalebar, inset map, etc.

**Comment by ChristopherTracey** [comment]
Ugh. I just read up on the issue (https://github.com/tidyverse/ggplot2/issues/2743).

Alternative idea: remove species names from map...

**Comment by tghoward** [comment]
new maps have simply removed gname. Continuing overhaul needed, but closing for now.
